// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCImfbOpDZJS3jYkczPr-0W5kyQgQlAgh0',
    appId: '1:187872035537:web:c4556b34ef73f890133bf0',
    messagingSenderId: '187872035537',
    projectId: 'office-login-ad146',
    authDomain: 'office-login-ad146.firebaseapp.com',
    storageBucket: 'office-login-ad146.appspot.com',
    measurementId: 'G-DLQKT9XLYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn-sFP17dac0vZ3G7mg_0JKVXcmfEGMeI',
    appId: '1:187872035537:android:3dc03e167b0db6dc133bf0',
    messagingSenderId: '187872035537',
    projectId: 'office-login-ad146',
    storageBucket: 'office-login-ad146.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo-VfAsPZqZya6CiERfTmWfBRkDoCJZFg',
    appId: '1:187872035537:ios:fbd815b8046f61e2133bf0',
    messagingSenderId: '187872035537',
    projectId: 'office-login-ad146',
    storageBucket: 'office-login-ad146.appspot.com',
    iosBundleId: 'com.example.officeLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo-VfAsPZqZya6CiERfTmWfBRkDoCJZFg',
    appId: '1:187872035537:ios:fbd815b8046f61e2133bf0',
    messagingSenderId: '187872035537',
    projectId: 'office-login-ad146',
    storageBucket: 'office-login-ad146.appspot.com',
    iosBundleId: 'com.example.officeLogin',
  );
}
